### ISSUE TITLE
Access log '/opt/dnssafety/var/log/access.log' does not exist, please ensure the dsdnsd daemon is up and running!

### ISSUE THREAD

**Issue by craigusus** [diladele/dnssafety#430]
Hi,
Running fresh install on Raspberry Pi. The access.log file is not being created.

```
Traceback (most recent call last):
  File "/opt/dnssafety-ui/var/console/traffic/views/summary.py", line 55, in get_context_data
    period, prefix = self.get_period()
  File "/opt/dnssafety-ui/var/console/traffic/views/mixins.py", line 98, in get_period
    regenerate_now()
  File "/opt/dnssafety-ui/var/console/traffic/views/mixins.py", line 69, in regenerate_now
    c.collect()
  File "/opt/dnssafety-ui/var/console/_domain/traffic/collect/collector_now.py", line 36, in collect
    entries = self.read_entries(where, lines_limit)
  File "/opt/dnssafety-ui/var/console/_domain/traffic/collect/collector_now.py", line 70, in read_entries
    raise Exception("Access log '%s' does not exist, please ensure the dsdnsd daemon is up and running!" % self.access_log)
Exception: Access log '/opt/dnssafety/var/log/access.log' does not exist, please ensure the dsdnsd daemon is up and running!
```
![Screenshot 2020-01-03 at 10 52 01](https://user-images.githubusercontent.com/6324863/71719716-1afaf000-2e17-11ea-84e4-e4ba2aa86c61.png)
![Screenshot 2020-01-03 at 10 39 13](https://user-images.githubusercontent.com/6324863/71719209-85129580-2e15-11ea-9bb1-7791413ef6da.png)
![Screenshot 2020-01-03 at 10 39 36](https://user-images.githubusercontent.com/6324863/71719215-8ba10d00-2e15-11ea-81f1-bc4f5bf82e1f.png)

/opt/dnssafety-ui/var/log/cron_report.log is not being created either...

![Screenshot 2020-01-03 at 10 40 35](https://user-images.githubusercontent.com/6324863/71719243-a4112780-2e15-11ea-8f34-5b95126385f7.png)

dsdnsd is running...
```
pi@dns:~ $ systemctl status dsdnsd.service
● dsdnsd.service - DNS Safety Filter
   Loaded: loaded (/etc/systemd/system/dsdnsd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-01-03 10:31:13 GMT; 3min 13s ago
     Docs: https://www.dnssafety.io
 Main PID: 456 (dsdnsd)
    Tasks: 11 (limit: 4915)
   Memory: 279.3M
   CGroup: /system.slice/dsdnsd.service
           └─456 /opt/dnssafety/bin/dsdnsd
```

**Comment by ra-at-diladele-com** [comment]
Hello Craig,

Try running one dns lookup over that server..

Best regards,
Rafael Akchurin

Op 3 jan. 2020 om 11:56 heeft Craig <notifications@github.com> het volgende geschreven:

﻿

Hi,
Running fresh install on Raspberry Pi. The access.log file is not being created.

Traceback (most recent call last):
  File "/opt/dnssafety-ui/var/console/traffic/views/summary.py", line 55, in get_context_data
    period, prefix = self.get_period()
  File "/opt/dnssafety-ui/var/console/traffic/views/mixins.py", line 98, in get_period
    regenerate_now()
  File "/opt/dnssafety-ui/var/console/traffic/views/mixins.py", line 69, in regenerate_now
    c.collect()
  File "/opt/dnssafety-ui/var/console/_domain/traffic/collect/collector_now.py", line 36, in collect
    entries = self.read_entries(where, lines_limit)
  File "/opt/dnssafety-ui/var/console/_domain/traffic/collect/collector_now.py", line 70, in read_entries
    raise Exception("Access log '%s' does not exist, please ensure the dsdnsd daemon is up and running!" % self.access_log)
Exception: Access log '/opt/dnssafety/var/log/access.log' does not exist, please ensure the dsdnsd daemon is up and running!


[Screenshot 2020-01-03 at 10 52 01]<https://user-images.githubusercontent.com/6324863/71719716-1afaf000-2e17-11ea-84e4-e4ba2aa86c61.png>
[Screenshot 2020-01-03 at 10 39 13]<https://user-images.githubusercontent.com/6324863/71719209-85129580-2e15-11ea-9bb1-7791413ef6da.png>
[Screenshot 2020-01-03 at 10 39 36]<https://user-images.githubusercontent.com/6324863/71719215-8ba10d00-2e15-11ea-81f1-bc4f5bf82e1f.png>

/opt/dnssafety-ui/var/log/cron_report.log is not being created either...

[Screenshot 2020-01-03 at 10 40 35]<https://user-images.githubusercontent.com/6324863/71719243-a4112780-2e15-11ea-8f34-5b95126385f7.png>

dsdnsd is running...

pi@dns:~ $ systemctl status dsdnsd.service
● dsdnsd.service - DNS Safety Filter
   Loaded: loaded (/etc/systemd/system/dsdnsd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-01-03 10:31:13 GMT; 3min 13s ago
     Docs: https://www.dnssafety.io
 Main PID: 456 (dsdnsd)
    Tasks: 11 (limit: 4915)
   Memory: 279.3M
   CGroup: /system.slice/dsdnsd.service
           └─456 /opt/dnssafety/bin/dsdnsd

**Comment by ra-at-diladele-com** [comment]
Also the reporting will run once per day thus cron_report.log will appear only tomorrow.

**Comment by craigusus** [comment]
Ah yes! All working, sorry.
Thanks for the quick response!
